---

- name: configure adrci lsnr
  shell: |
    source /home/grid/.bash_profile
    echo "set home diag/tnslsnr/{{ ansible_hostname |lower }}/{{ netca_lsnr_name |lower }}
    set control (SHORTP_POLICY=168)
    set control (LONGP_POLICY=168)" | {{ oracle_home }}/bin/adrci
  become: true
  become_user: grid

