oracle.install.responseFileVersion=/oracle/install/rspfmt_dbinstall_response_schema_v12.1.0
oracle.install.option=INSTALL_DB_SWONLY
UNIX_GROUP_NAME=oinstall
SELECTED_LANGUAGES=en
oracle.install.db.InstallEdition=SE2
oracle.install.db.DBA_GROUP=dba
oracle.install.db.BACKUPDBA_GROUP=dba
oracle.install.db.DGDBA_GROUP=dba
oracle.install.db.KMDBA_GROUP=dba
oracle.install.db.CLUSTER_NODES={{ grid_publicnodes.replace(' ',',') }}
SECURITY_UPDATES_VIA_MYORACLESUPPORT=false
DECLINE_SECURITY_UPDATES=true
INVENTORY_LOCATION={{ oracle_root }}/oraInventory
ORACLE_BASE={{ oracle_base }}
ORACLE_HOME={{ oracle_home }}
