---

- name: install python-simplejson
  yum: name=python-simplejson state=latest 
#  environment:
#       http_proxy: "{{ proxy }}"

- name: upgrade all packages
  yum: name=* state=latest
#  environment:
#     http_proxy: "{{ proxy }}"

- name: include rhel/centos spec
  include: rhel.yaml
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: include oracle linux spec
  include: oraclelinux.yaml
  when: (ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "7")

- name: install python-selinux
  yum: name=libselinux-python state=installed
#  environment:
#      http_proxy: "{{ proxy }}"

- name: add public key to authorized_key file of root
  authorized_key: user=root state=present key="{{ lookup('file','/root/.ssh/id_rsa.pub') }}"


