---

- name: change binaries owner to grid
  file: path={{ item }} owner=grid group=oinstall
  with_items:
    - "{{ patch_dir }}/{{ grid_psu }}"

- name: unzip GRID psu
  unarchive: src={{ patch_dir }}/{{ grid_psu }} dest={{ patch_dir }} remote_src=yes
  become: true
  become_user: grid

- name: set grid home permissions
  file: path={{ grid_home}} owner=grid group=oinstall

- name: set patch list
  find: 
    paths: "{{ patch_dir }}/{{ grid_psu_number }}"
    patterns: "^[1-9].*"
    recurse: no
    use_regex: yes
    file_type: directory
  register: patchlist

- name: update Opatch
  unarchive: src={{ patch_dir }}/{{ opatch_patch }} dest={{ grid_home }} remote_src=yes exclude=PatchSearch.xml
  become: true
  become_user: grid

- name: patch conflict detection
  shell: "export ORACLE_HOME={{ grid_home }}; $ORACLE_HOME/OPatch/opatch prereq CheckConflictAgainstOHWithDetail -ph {{ item.path }}"
  become: true
  become_user: grid
  register: conflict_detection
  failed_when: "'Prereq \"checkConflictAgainstOHWithDetail\" passed.' not in conflict_detection.stdout"
  with_items: 
    "{{ patchlist.files }}"

- name: chmod generatePsuGridRespFile.sh 11
  file: path={{ patch_dir }}/generatePsuGridRespFile.sh owner=grid group=oinstall mode=0755
  when: major_version == 11

- name: generate response file 11
  shell: |
    source /home/grid/.bash_profile
    {{ patch_dir }}/generatePsuGridRespFile.sh {{ grid_home }} {{ patch_dir }}
  become: true
  become_user: grid
  when: major_version == 11

- name: roothas prepatch 11
  shell: "{{ grid_home }}/crs/install/roothas.pl -unlock"
  when: major_version == 11

- name: roothas prepatch 12
  shell: "{{ grid_home }}/crs/install/roothas.pl -prepatch"
  when: major_version == 12

- name: apply psu 11
  shell: "export ORACLE_HOME={{ grid_home}}; $ORACLE_HOME/OPatch/opatch apply {{ item.path }} -silent -ocmrf {{ patch_dir }}/gridpsu.rsp"
  become: true
  become_user: grid
  register: apply_psu
  failed_when: "'successfully applied.' not in apply_psu.stdout"
  with_items:
    "{{ patchlist.files }}"
  when: major_version == 11

- name: apply psu 12
  shell: "export ORACLE_HOME={{ grid_home}}; $ORACLE_HOME/OPatch/opatch apply {{ item.path }} -silent"
  become: true
  become_user: grid
  register: apply_psu
  failed_when: "'successfully applied.' not in apply_psu.stdout"
  with_items:
    "{{ patchlist.files }}"
  when: major_version == 12

- name: roothas postpatch 11
  shell: "{{ grid_home }}/crs/install/roothas.pl -patch"
  when: major_version == 11

- name: roothas postpatch 12
  shell: "{{ grid_home }}/crs/install/roothas.pl -postpatch"
  when: major_version == 12

- name: clean unzipped
  file: path={{ patch_dir }}/{{ grid_psu_number }} state=absent
